# Generated by Django 3.2.5 on 2021-10-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('range', models.PositiveSmallIntegerField()),
                ('seats', models.PositiveSmallIntegerField()),
                ('luggage', models.PositiveSmallIntegerField()),
                ('image', models.URLField()),
            ],
        ),
    ]
