# Generated by Django 3.2.5 on 2021-10-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0004_auto_20211018_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('site', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('hours_from', models.TimeField()),
                ('hours_to', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='carhire.location')),
            ],
            options={
                'ordering': ('location', 'day', 'hours_from'),
                'unique_together': {('location', 'day', 'hours_from', 'hours_to')},
            },
        ),
    ]
