# Generated by Django 3.2.5 on 2021-10-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0006_alter_openingtimes_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='postcode',
            field=models.CharField(default='a', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
