# Generated by Django 3.2.5 on 2021-10-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0007_auto_20211019_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='tel',
            field=models.CharField(default='+44 (0) 1234 567890', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
