# Generated by Django 3.2.5 on 2021-10-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0008_auto_20211019_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='map',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
