# Generated by Django 3.2.5 on 2021-10-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0009_location_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
