# Generated by Django 3.2.5 on 2021-10-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0011_rename_car_cartype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carhire.location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carhire.cartype')),
            ],
        ),
    ]
