# Generated by Django 3.2.5 on 2021-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0013_location_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coords',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
