# Generated by Django 3.2.5 on 2021-10-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0014_location_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='coords',
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='long',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
