# Generated by Django 3.2.5 on 2021-10-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0016_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dropoff',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.DateTimeField(),
        ),
    ]
