# Generated by Django 3.2.5 on 2021-10-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0017_auto_20211025_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='base_price',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
