# Generated by Django 3.2.5 on 2021-10-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0018_cartype_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='price_factor',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='base_price',
            field=models.FloatField(),
        ),
    ]
