# Generated by Django 3.2.5 on 2021-11-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0020_rename_base_price_cartype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(blank=True, default='123456789', max_length=9, null=True),
        ),
    ]
