# Generated by Django 3.2.5 on 2021-11-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0021_booking_booking_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(default='123456789', max_length=9, unique=True),
        ),
    ]
